[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "Poppins"

[server]
enableCORS = false
enableXsrfProtection = true
headless = true
port = 5000

[browser]
gatherUsageStats = false
